Repository cardano-foundation/cf-explorer-api, pull requests merged in 2024-09, with the labels that each got.

#1355 Feat/met 2239 update url wineries public key
  README.md
  docker-compose.yml
  src/main/java/org/cardanofoundation/explorer/api/service/impl/BolnisiMetadataServiceImpl.java
  src/main/resources/config/application-dev.yaml
  src/main/resources/config/application-prod.yaml
  src/test/java/org/cardanofoundation/explorer/api/service/BolnisiMetadataServiceTest.java
Labels: 1.9.0

#1360 feat: calculate carbon emissions of an address or stake address
  src/main/java/org/cardanofoundation/explorer/api/common/constant/CommonConstant.java
  src/main/java/org/cardanofoundation/explorer/api/controller/MiCARController.java
  src/main/java/org/cardanofoundation/explorer/api/model/response/micar/AddressCarbonEmissionResponse.java
  src/main/java/org/cardanofoundation/explorer/api/repository/ledgersyncagg/AddressTxCountRepository.java
  src/main/java/org/cardanofoundation/explorer/api/repository/ledgersyncagg/StakeAddressTxCountRepository.java
  src/main/java/org/cardanofoundation/explorer/api/service/MiCARService.java
  src/main/java/org/cardanofoundation/explorer/api/service/impl/MiCARServiceImpl.java
  src/test/java/org/cardanofoundation/explorer/api/controller/MiCARControllerTest.java
  src/test/java/org/cardanofoundation/explorer/api/service/MiCARServiceTest.java
Labels: 1.9.0

#1374 fix: return null if the address or stake address does not exist
  src/main/java/org/cardanofoundation/explorer/api/service/impl/MiCARServiceImpl.java
Labels: 1.9.0

#1376 fix: several fields in off-chain data might be null
  src/main/java/org/cardanofoundation/explorer/api/service/impl/GovernanceActionServiceImpl.java
  src/test/java/org/cardanofoundation/explorer/api/service/GovActionServiceTest.java
Labels: 1.9.0

#1358 feat: searching for staking lifecycle page
  src/main/java/org/cardanofoundation/explorer/api/controller/SearchController.java
  src/main/java/org/cardanofoundation/explorer/api/model/response/search/AddressSearchResponse.java
  src/main/java/org/cardanofoundation/explorer/api/model/response/search/SearchStakingLifecycle.java
  src/main/java/org/cardanofoundation/explorer/api/repository/ledgersync/PoolHashRepository.java
  src/main/java/org/cardanofoundation/explorer/api/service/SearchService.java
  src/main/java/org/cardanofoundation/explorer/api/service/impl/SearchServiceImpl.java
  src/test/java/org/cardanofoundation/explorer/api/controller/SearchControllerTest.java
  src/test/java/org/cardanofoundation/explorer/api/service/SearchServiceTest.java
Labels: 1.9.0

#1348 1.8.0
  pom.xml
  src/main/java/org/cardanofoundation/explorer/api/controller/StakeKeyController.java
  src/main/java/org/cardanofoundation/explorer/api/model/response/token/TokenFilterResponse.java
  src/main/java/org/cardanofoundation/explorer/api/projection/TokenProjection.java
  src/main/java/org/cardanofoundation/explorer/api/repository/explorer/TokenInfoRepository.java
  src/main/java/org/cardanofoundation/explorer/api/repository/ledgersync/CommitteeRegistrationRepository.java
  src/main/java/org/cardanofoundation/explorer/api/repository/ledgersync/MultiAssetRepository.java
  src/main/java/org/cardanofoundation/explorer/api/repository/ledgersyncagg/StakeAddressBalanceRepository.java
  src/main/java/org/cardanofoundation/explorer/api/service/impl/DRepServiceImpl.java
  src/main/java/org/cardanofoundation/explorer/api/service/impl/StakeKeyServiceImpl.java
  src/main/java/org/cardanofoundation/explorer/api/service/impl/TokenServiceImpl.java
  src/test/java/org/cardanofoundation/explorer/api/service/StakeKeyServiceTest.java
  src/test/java/org/cardanofoundation/explorer/api/service/TokenServiceTest.java
Labels: 1.8.0

#1387 Refactor/met 2361 remove relevant logic related to token info data
  src/main/java/org/cardanofoundation/explorer/api/controller/AddressController.java
  src/main/java/org/cardanofoundation/explorer/api/controller/StakeKeyController.java
  src/main/java/org/cardanofoundation/explorer/api/controller/TokenController.java
  src/main/java/org/cardanofoundation/explorer/api/model/response/token/TokenResponse.java
  src/main/java/org/cardanofoundation/explorer/api/repository/explorer/TokenInfoRepository.java
  src/main/java/org/cardanofoundation/explorer/api/repository/ledgersync/DelegationRepository.java
  src/main/java/org/cardanofoundation/explorer/api/repository/ledgersync/RewardRepository.java
  src/main/java/org/cardanofoundation/explorer/api/repository/ledgersync/StakeAddressRepository.java
  src/main/java/org/cardanofoundation/explorer/api/repository/ledgersync/WithdrawalRepository.java
  src/main/java/org/cardanofoundation/explorer/api/repository/ledgersyncagg/LatestTokenBalanceRepository.java
  src/main/java/org/cardanofoundation/explorer/api/repository/ledgersyncagg/TopAddressBalanceRepository.java
  src/main/java/org/cardanofoundation/explorer/api/repository/ledgersyncagg/TopStakeAddressBalanceRepository.java
  src/main/java/org/cardanofoundation/explorer/api/service/AddressService.java
  src/main/java/org/cardanofoundation/explorer/api/service/StakeKeyService.java
  src/main/java/org/cardanofoundation/explorer/api/service/TokenService.java
  src/main/java/org/cardanofoundation/explorer/api/service/impl/AddressServiceImpl.java
  src/main/java/org/cardanofoundation/explorer/api/service/impl/StakeKeyServiceImpl.java
  src/main/java/org/cardanofoundation/explorer/api/service/impl/TokenServiceImpl.java
  src/test/java/org/cardanofoundation/explorer/api/controller/AddressControllerTest.java
  src/test/java/org/cardanofoundation/explorer/api/controller/StakeKeyControllerTest.java
  src/test/java/org/cardanofoundation/explorer/api/controller/TokenControllerTest.java
  src/test/java/org/cardanofoundation/explorer/api/service/AddressServiceTest.java
  src/test/java/org/cardanofoundation/explorer/api/service/StakeKeyServiceTest.java
  src/test/java/org/cardanofoundation/explorer/api/service/TokenServiceTest.java
Labels: dev_test

#1385 refactor: remove top ada holders
  src/main/java/org/cardanofoundation/explorer/api/controller/AddressController.java
  src/main/java/org/cardanofoundation/explorer/api/controller/StakeKeyController.java
  src/main/java/org/cardanofoundation/explorer/api/repository/ledgersync/DelegationRepository.java
  src/main/java/org/cardanofoundation/explorer/api/repository/ledgersync/RewardRepository.java
  src/main/java/org/cardanofoundation/explorer/api/repository/ledgersync/StakeAddressRepository.java
  src/main/java/org/cardanofoundation/explorer/api/repository/ledgersync/WithdrawalRepository.java
  src/main/java/org/cardanofoundation/explorer/api/repository/ledgersyncagg/TopAddressBalanceRepository.java
  src/main/java/org/cardanofoundation/explorer/api/repository/ledgersyncagg/TopStakeAddressBalanceRepository.java
  src/main/java/org/cardanofoundation/explorer/api/service/AddressService.java
  src/main/java/org/cardanofoundation/explorer/api/service/StakeKeyService.java
  src/main/java/org/cardanofoundation/explorer/api/service/impl/AddressServiceImpl.java
  src/main/java/org/cardanofoundation/explorer/api/service/impl/StakeKeyServiceImpl.java
  src/test/java/org/cardanofoundation/explorer/api/controller/AddressControllerTest.java
  src/test/java/org/cardanofoundation/explorer/api/controller/StakeKeyControllerTest.java
  src/test/java/org/cardanofoundation/explorer/api/service/AddressServiceTest.java
  src/test/java/org/cardanofoundation/explorer/api/service/StakeKeyServiceTest.java
Labels: dev_test

#1389 feat: get bolnisi numbers
  src/main/java/org/cardanofoundation/explorer/api/controller/BolnisiController.java
  src/main/java/org/cardanofoundation/explorer/api/model/response/BolnisiProjectNumberResponse.java
  src/main/java/org/cardanofoundation/explorer/api/service/BolnisiMetadataService.java
  src/main/java/org/cardanofoundation/explorer/api/service/impl/BolnisiMetadataServiceImpl.java
  src/test/java/org/cardanofoundation/explorer/api/controller/BolnisiControllerTest.java
Labels: dev_test

#1395 refactor: remove columns block table
  src/main/java/org/cardanofoundation/explorer/api/service/impl/BlockServiceImpl.java
Labels: dev_test

#1393 refactor: remove columns transaction table
  src/main/java/org/cardanofoundation/explorer/api/service/impl/TxServiceImpl.java
  src/test/java/org/cardanofoundation/explorer/api/service/TxServiceTest.java
Labels: dev_test

#1396 feat: add supply and pots controller
  src/main/java/org/cardanofoundation/explorer/api/common/constant/CommonConstant.java
  src/main/java/org/cardanofoundation/explorer/api/controller/PotsController.java
  src/main/java/org/cardanofoundation/explorer/api/controller/SupplyController.java
  src/main/java/org/cardanofoundation/explorer/api/model/response/PotsOverviewResponse.java
  src/main/java/org/cardanofoundation/explorer/api/model/response/dashboard/EpochSummary.java
  src/main/java/org/cardanofoundation/explorer/api/repository/ledgersync/AdaPotsRepository.java
  src/main/java/org/cardanofoundation/explorer/api/service/PotsService.java
  src/main/java/org/cardanofoundation/explorer/api/service/SupplyService.java
  src/main/java/org/cardanofoundation/explorer/api/service/impl/EpochServiceImpl.java
  src/main/java/org/cardanofoundation/explorer/api/service/impl/PotsServiceImpl.java
  src/main/java/org/cardanofoundation/explorer/api/service/impl/SupplyServiceImpl.java
  src/test/java/org/cardanofoundation/explorer/api/controller/PotsControllerTest.java
  src/test/java/org/cardanofoundation/explorer/api/controller/SupplyControllerTest.java
  src/test/java/org/cardanofoundation/explorer/api/service/EpochServiceTest.java
  src/test/java/org/cardanofoundation/explorer/api/service/PotsServiceTest.java
  src/test/java/org/cardanofoundation/explorer/api/service/SupplyServiceTest.java
  src/test/java/org/cardanofoundation/explorer/api/service/WebSocketServiceTest.java
Labels: dev_test
